# Rubyのイメージをベースにする
FROM ruby:3.2.3

# 環境変数の設定
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要なパッケージのインストール
RUN apt-get update -qq \
 && apt-get install -y \
      build-essential \
      libpq-dev \
      nodejs \
      yarn \
      vim \
      python3-dev \
      python3-pip \
      python3 \
      python3-venv \
      wget \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Python仮想環境の設定
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Pythonパッケージのインストール
RUN pip3 install --upgrade pip setuptools wheel \
 && pip3 install pillow opencv-python-headless
 
# Node.jsとYarnのインストール
RUN apt-get update -qq \
 && apt-get install -y ca-certificates curl gnupg \
 && mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
 && NODE_MAJOR=20 \
 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
 && wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
 && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
 && apt-get update -qq \
 && apt-get install -y --no-install-recommends \
      nodejs \
      yarn \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# ワーキングディレクトリの設定
RUN mkdir /myapp
WORKDIR /myapp

# パッケージのインストール
RUN yarn install

# Rubyの依存関係をインストール
RUN gem install bundler

# ホストマシンのファイルをコンテナにコピー
COPY . /myapp

# `esbuild`と`nodemon`のインストール
RUN yarn add --dev nodemon esbuild

# パスの確認とエラー対処のためのスクリプト
RUN echo 'export PATH=$(yarn bin):$PATH' >> ~/.bashrc

# アプリケーションサーバーの起動コマンド
CMD ["sh", "-c", "source ~/.bashrc && bundle exec foreman start -f Procfile.dev"]